name: FRadioPlayer
options:
  bundleIdPrefix: com.fethica
  deploymentTarget:
    iOS: 10.0
targets:
  FRadioPlayer:
    type: framework
    platform: [iOS]
    sources: Sources/FRadioPlayer
    scheme: {}
    settings:
      INFOPLIST_FILE: CarthageInfo.plist
